# Generated by Django 4.1.5 on 2023-01-31 16:49

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='A label for URL config.', max_length=31, populate_from=['name'])),
            ],
        ),
    ]
